Add an exit to the build

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -18,7 +18,9 @@ jobs:
     - name: "Update Draft Name"
       run: |
         if [ -z $(ls draft-* rfc* | grep -v draft-todo-yourname-protocol.md) ]; then
-          echo "Start working by renaming your draft"
+          echo "It is OK for the first build to fail."
+          echo "Start working by renaming your draft."
+          exit 1
         fi
         for i in draft-*; do
           sed -i -e "s/draft-todo-yourname-protocol-latest/${i%.md}-latest/g" "$i"
